### ISSUE TITLE
openssl with specific condition does not work.

### ISSUE THREAD

**Issue by greymd** [greymd/ttcopy#44]
from #42 by @fmyokosuka

> **Problems with openssl**
> 
> I understood the majority.
> But I can not write long sentences.
> Please look at this.
> ↓
> http://rods777.ddo.jp/~b954173/memo/ttcopy_openssl_memo_20170310.txt

**Comment by greymd** [comment]
The reason why we are using `$_TTCP_ENCRYPT_ALGORITHM` is, for testing.
In order to increase test coverage, there is the test case for wrong algorithm.
https://github.com/greymd/ttcopy/blob/master/test/test.sh#L388

but, as @fmyokosuka mentioned, we can use `enc` instead of `-e` option.
It seems `enc` is more compatible to various `openssl` versions.

**Comment by greymd** [comment]
（というわけで`-e`よりも`enc`つかう方向の方が良さそうっすね！ @fmyokosuka さん度々ありがとうございます。。）

**Comment by greymd** [comment]
I have not tried it yet. but it might work.
```diff
diff --git a/lib/ttcp b/lib/ttcp
index e4bf2a4..d024b23 100644
--- a/lib/ttcp
+++ b/lib/ttcp
@@ -372,7 +372,7 @@ __ttcp::http_client () {
 __ttcp::encode () {
     local _key="$1"
     local _iv="0"
-    gzip | openssl "${_TTCP_ENCRYPT_ALGORITHM}" -e -K "$_key" -iv "$_iv"
+    gzip | openssl enc "${_TTCP_ENCRYPT_ALGORITHM}" -K "$_key" -iv "$_iv"
 }
```

**Comment by greymd** [comment]
Hi @fmyokosuka
Could you tell us the openssl's version?

**Comment by fmyokosuka** [comment]
This is my openssl.

[root@h ~]# cat /etc/redhat-release
CentOS release 6.3 (Final)
[root@h ~]# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

fmyokosuka uname -a
MINGW32_NT-6.1 I1001643 2.7.0(0.307/5/3) 2017-02-17 13:59 i686 Msys
fmyokosuka openssl version
OpenSSL 1.0.2k  26 Jan 2017
fmyokosuka

[root@cmu4 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.7 (Tikanga)
[root@cmu4 ~]# openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

**Comment by greymd** [comment]
Hi @fmyokosuka 
hmm... I cannot re-produce the openssl's bug... 😭 
I tried ttcopy at the similar environment, but it seems it works fine..
Could you tell me the the environment's information further more?

* OS
* bash version
* curl version
* openssl version

```
$ cat /etc/redhat-release
CentOS release 5.7 (Final)
$ curl --version
curl 7.21.3 (x86_64-unknown-linux-gnu) libcurl/7.21.3 OpenSSL/0.9.8n zlib/1.2.3 libidn/0.6.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: IDN Largefile NTLM SSL libz
$ openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
$ bash --version
GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.
$ ttcopy --version
2.2.1
$ seq 10 20 | ttcopy
Copied!
$ ttpaste
10
11
12
13
14
15
16
17
18
19
20
```

**Comment by fmyokosuka** [comment]
I'm sorry!
Perhaps my operation is wrong.
I will try again with ttcopy 2.2.1.

**Comment by fmyokosuka** [comment]
**Test report of ttcopy 2.2.1**

### CentOS 6.3 OK

### RHEL7.2 OK

### Windows/Msys2 OK

### RHEL5.7 NG 

　https://transfer.sh ←OK
　https://cl1p.net　←NG
　Succeeded by adding the -k option to curl.
　↓
　curl -x http://hehe.hihihi.co.jp:9999 -k -X POST https://cl1p.net/ttcopy/…

bash-3.2$ ttcopy --version
2.2.1
bash-3.2$ seq 3 | ttcopy
Failed to save the content url 
bash-3.2$ uname -a
Linux cmu3 2.6.18-274.el5 #1 SMP Fri Jul 8 17:36:59 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
bash-3.2$ openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
bash-3.2$ curl --version
curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
bash-3.2$ bash --version
GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.
bash-3.2$ cat /etc/redhat-*
cat: /etc/redhat-lsb: Is a directory
Red Hat Enterprise Linux Server release 5.7 (Tikanga)
bash-3.2$
bash-3.2$ head -1 $(which ttcopy)
#!/bin/bash -x
bash-3.2$ seq 3 | ttcopy ＞xxxxxx  2＞&1
bash-3.2$ grep curl xxxxxx
++ _TTCP_DEPENDENCIES='yes openssl curl perl gzip'
++ _TTCP_HTTP_CLIENT=curl
+ type curl
++ echo 'curl -x http://hehe.hihihi.co.jp:9999'
+ _HTTP_CLIENT='curl -x http://hehe.hihihi.co.jp:9999'
++ curl -x http://hehe.hihihi.co.jp:9999 -so- --fail --upload-file - https://transfer.sh/3cae0922acd984938e1298c47e0a74d54b579ed5343f3334ba411c6750dccd54
+ curl -x http://hehe.hihihi.co.jp:9999 -s -X POST https://cl1p.net/ttcopy/cf8732489268a8c75b6ee3f7c51d82d97f2740a992719e20472d99cd00b7adb8 --fail --data 'content=TTCP[NYg6bo1-AugZcBLLxL4UvKDZ-3w_Yv2eiOFjIk7xhyL-eUX3dIaP4nRwjQG79Z_sIod2l0IWxH6koG5Jz8g3TCyO-4BWIsHtHxCx-hPYonqEZcFJNUMv8U1RDHLA37XZywtYsePOleXIir-A4g-lDg==]'
bash-3.2$
bash-3.2$ curl -x http://hehe.hihihi.co.jp:9999 -X POST https://cl1p.net/ttcopy/cf8732489268a8c75b6ee3f7c51d82d97f2740a992719e20472d99cd00b7adb8 --fail --data 'content=TTCP[NYg6bo1-A
ugZcBLLxL4UvKDZ-3w_Yv2eiOFjIk7xhyL-eUX3dIaP4nRwjQG79Z_sIod2l0IWxH6koG5Jz8g3TCyO-4BWIsHtHxCx-hPYonqEZcFJNUMv8U1RDHLA37XZywtYsePOleXIir-A4g-lDg==]'
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). The default
 bundle is named curl-ca-bundle.crt; you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
bash-3.2$
bash-3.2$ curl -x http://hehe.hihihi.co.jp:9999 -k -X POST https://cl1p.net/ttcopy/cf8732489268a8c75b6ee3f7c51d82d97f2740a992719e20472d99cd00b7adb8 --fail --data 'content=TTCP[NYg6bo
1-AugZcBLLxL4UvKDZ-3w_Yv2eiOFjIk7xhyL-eUX3dIaP4nRwjQG79Z_sIod2l0IWxH6koG5Jz8g3TCyO-4BWIsHtHxCx-hPYonqEZcFJNUMv8U1RDHLA37XZywtYsePOleXIir-A4g-lDg==]'
html＞
：
＜p＞On any other computer or smartphone enter in http://cl1p.net/ttcopy/cf8732489268a8c75b6ee3f7c51d82d97f2740a992719e20472d99cd00b7adb8 to retreive the content.＜/p＞
＜p＞Please note the information can be viewed only ＜b＞once＜/b＞, then it will be deleted.＜/p＞
：
＜/html＞
bash-3.2$ echo $?
0
bash-3.2$

**Comment by fmyokosuka** [comment]
RHEL5.7 NG→OK

bash-3.2$ diff ttcopy  ttcopy.org
46c46
< ${_HTTP_CLIENT} -s -k -X POST "$TTCP_CLIP_NET/$TTCP_ID_PREFIX/$TTCP_ID_CLIP" --fail --data "content=TTCP[$ENCRYPTED_TRANS_URL]" > /dev/null
---
> ${_HTTP_CLIENT} -s -X POST "$TTCP_CLIP_NET/$TTCP_ID_PREFIX/$TTCP_ID_CLIP" --fail --data "content=TTCP[$ENCRYPTED_TRANS_URL]" > /dev/null

bash-3.2$ diff ttpaste  ttpaste.org
42c42
< CLIP_BODY=$(${_HTTP_CLIENT} --fail -k -so- "$TTCP_CLIP_NET/$TTCP_ID_PREFIX/$TTCP_ID_CLIP" 2> /dev/null)
---
> CLIP_BODY=$(${_HTTP_CLIENT} --fail -so- "$TTCP_CLIP_NET/$TTCP_ID_PREFIX/$TTCP_ID_CLIP" 2> /dev/null)

bash-3.2$ curl --version
curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

bash-3.2$ openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

bash-3.2$ seq 3 | ttcopy
Copied!

bash-3.2$ ttpaste
1
2
3
bash-3.2$

**Comment by greymd** [comment]
@fmyokosuka  Thank you for investigations!

I guess, those curl and openssl do not support particular TLS/SSL protocols or particular cipher suites.
And this is why such the bug is happened.

Actually [curl with version 7.19 or less force to use SSLv3](https://www.miraclelinux.com/tech-blog/kr6fbj) in spite of that cl1p.net does not allow SSLv3. In addition, [openssl 0.9.8e uses SSLv3 without any intentional options](https://teratail.com/questions/9776).

Therefore, we would like to define  `curl` version around 7.19 and `openssl` version around `0.9.8e` as the smallest requirement for `ttcopy`.

Using `-k` option is not good idea because it may cause any information leakage.

By the way, editing `_TTCP_HTTP_CLIENT` environment variable can be one of the workaround.

```
[root@cd69dfba6f4e share]# export _TTCP_HTTP_CLIENT="curl -k"
[root@cd69dfba6f4e share]# seq 5 | ttcopy
Copied!
[root@cd69dfba6f4e share]# ttpaste
1
2
3
4
5
```

If you want to use `ttcopy` in the old environment, please choose this way on your own risk.
I would like to close this issue because there is no choices to resolve this issue.

Thank you very much for your cooperations❗️

**Comment by fmyokosuka** [comment]
Has completed. Thank you very much.

bash-3.2$ openssl version
OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
bash-3.2$ curl --version
curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
bash-3.2$ grep _TTCP_HTTP_CLIENT ttcopy/*
ttcopy/ttcp_activate.sh:    export _TTCP_HTTP_CLIENT="curl -k" # It's used by self-responsibility.
bash-3.2$ ttcopy --version
2.2.1
bash-3.2$ seq 3 | ttcopy
Copied!
bash-3.2$ ttpaste
1
2
3
bash-3.2$
